---
# tasks file for apache
- name: Install packages
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ pkgs }}"

- name: start and enable packages
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ pkgs }}"

- name: template tranfer
  template:
    src: index.html.j2
    dest: /var/www/html/index.php
  notify: restart httpd

- name: Open ports
  firewalld:
    service: "{{ item }}"
    state: enabled
    immediate: yes
    permanent: yes
  loop: "{{ rule }}"
